---
apiVersion: v2
name: agentic-sdlc-orchestrator-dev
description: Development release of Agentic SDLC Orchestrator
type: application
version: 0.1.0
dependencies:
  - name: agentic-sdlc-orchestrator
    version: 0.1.0
    repository: file://../../charts/agentic-sdlc-orchestrator
